name: PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  title:
    name: PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - run: node scripts/ci/pr-title.mjs
        env:
          TITLE: ${{ github.event.pull_request.title }}
